### ISSUE TITLE
[Bug] k8s的defaultMode的问题

### ISSUE THREAD

**Issue by withlin** [KubeOperator/KubePi#55]
**KubePi 版本**
v1.3.0

**Kubernetes 版本**
v1.20.6

**Bug 描述**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
      annotations: 
        prometheus.io/enabled: "true"
        prometheus.io/port: "9479"
        prometheus.io/metric_path: /metrics
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: exporter
        image: filebeat/filebeat:7.6.2
        imagePullPolicy: Always
        ports:
        - containerPort: 9479
        # resources:
        #   limits:
        #     memory: 50Mi
        #     cpu: 100m
        # command:
        # - sleep 
        # - 10000000
      - name: filebeat
        image: filebeat/filebeat:7.6.2
        imagePullPolicy: Always
        ports:
        - containerPort: 5066
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      
        securityContext:
          runAsUser: 0
          # If using Red Hat OpenShift uncomment this:
          #privileged: true
        resources:
          limits:
            memory: 1000Mi
            # cpu: 1000m
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: config
          mountPath: /etc/filebeat/system.yml
          readOnly: true
          subPath: system.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: cert
          mountPath: /etc/klog/credential.keystore
          subPath: credential.keystore
          readOnly: true
        - name: old-log
          mountPath: /data/logs
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
      - name: data
        hostPath:
          # When filebeat runs as non-root user, this directory needs to be writable by group (g+w).
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
      - name: old-log
        hostPath:
          path: /data/logs
          type: DirectoryOrCreate
      - name: cert
        secret:
          defaultMode: 0600
          secretName: filebeat-secret
```
提交该yaml，defaultMode: 0600 不行，不知道是不是json到yaml到后端有问题，具体代码我没看。要自己转成10进制才行
