### ISSUE TITLE
[Question]在k8s集群里面部署，无法使用webkubectl

### ISSUE THREAD

**Issue by seaurching** [KubeOperator/KubePi#91]
* 因为operator太重了，使用一个轻量的应用管理集群 *
我在k8s里面使用StatefulSets部署了一个有状态应用，使用ingress-nginx做为集群控制入口，ingress的配置文件也有websocket的配置，我在使用过程中发现无法使用webkubectl这个功能。不知道官方有没有解决办法。
下面是ingress配置
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-canary-behavior: sticky
    nginx.ingress.kubernetes.io/affinity-mode: persistent
  name: kubepi
  namespace: kube-public
spec:
  defaultBackend:
    service:
      name: kubepi
      port:
        number: 80
  rules:
  - host: kubepi.wps.cn
    http:
      paths:
      - backend:
          service:
            name: kubepi
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - {}
```
ingress-controller里面的nginx.conf看了一下是有关于websocket的配置。这部分配置使用nginx反向代理到kubepi是可以正常进入webkubectl的，在集群里面就不行。
```
http{
    .......
        map $http_upgrade $connection_upgrade {                                                                                  
                default          upgrade;                                                                                        
                                                                                                                                 
                # See http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive                                      
                ''               '';                                                                                             
                                                                                                                                 
        }   
        server {
                ........
                location / {
                        proxy_set_header                        Upgrade           $http_upgrade;                        
                        proxy_set_header                        Connection        $connection_upgrade;                
                               
                }
        }
```
